spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#        type: trace
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver